name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: dxcpocregistry.azurecr.io # default: index.docker.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}  

    # Commit and push all changed files.
    - name: Build and Push Docker Images to Azure Repo
      if: github.event_name == 'push'
      run: |
        docker build . -t dxcpocregistry.azurecr.io/node-js-hello-world:v1
        docker push dxcpocregistry.azurecr.io/node-js-hello-world:v1