name: Continuous Integration
on:
  push:
    branches:
      - main
env:
  SMARTCHECK_URL: https://40.76.172.231/api     
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/docker-login@v1
      with:
        login-server: dxcpocregistry.azurecr.io # default: index.docker.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}  

    - name: jq 
      uses: sergeysova/jq-action@v2
      id: version
      with:
        cmd: 'jq .version package.json -r'
        

    #Builds the docker image and push to ACR
    - name: Build and Push Docker Images to Azure Repo
      if: github.event_name == 'push'
      run: |
        raw=$(curl -sk -X POST $SMARTCHECK_URL/sessions -H 'Content-type:application/json' -H 'X-Api-Version:2018-05-01' -d '{"user": {"userid":${{ secrets.SMARTCHECK_USERNAME }},"password":${{ secrets.SMARTCHECK_PASSWORD }}}}')
        token=$(cat raw | jq .token)
        echo $token
        docker build . -t dxcpocregistry.azurecr.io/node-js-app:v1
        docker push dxcpocregistry.azurecr.io/node-js-app:v1